### ISSUE TITLE
Documentation TODO

### ISSUE THREAD

**Issue by Mitchell-Borders** [HagenSR/byte_le_royale_2022#233]
**NOTE:** There may be more shown than is neccessary, I just went down the files and put them here
### Objects
- [x] Consumable
- [x] Gun
- [x] Item
- [x] Money
- [x] Upgrade
- [x] Bullet
- [x] Damaging_object
- [x] Grenade
- [x] Moving_object
- [x] Shooter
- [x] Action
- [x] Door
- [x] Enums
- [x] game_board
- [x] game_object
- [x] Hitbox
- [x] map_object
- [x] player
- [x] ray
- [x] stats
- [x] telporter
- [x] wall
### Controllers
- [x] controller
- [x] Grenade_controller
- [x] interact_controller
- [x] Kill_boundary_controller
- [x] loot_generation_controller
- [x] Master_controller
- [x] Movement_controller
- [x] reload_controller
- [x] shoot_controller
- [x] teleporter_controller
- [x] upgrade_controller
- [x] Use_controller
### Utils
- [x] calculate_new_location
- [x] collision_detection
- [x] Engine_thread
- [x] Generate_game
- [x] Helpers
- [x] Item_gen_utils
- [x] Partition_grid
- [x] Player_utils
- [x] ray_utils
- [x] Validation
